title: "javascript:void(0);"
author: "Kyle J. Kemp"
description: "I post things"
#subheading: "Most times"
more: "read more"
url: "http://blog.seiyria.com"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "seiblog"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/seiyria/"
  - twitter: "https://twitter.com/seiyria/"
  - google-plus: "https://plus.google.com/+KyleJKemp"
  - reddit: "https://www.reddit.com/user/seiyria/"
#  - youtube: "https://www.youtube.com/user/m"
  - steam: "http://steamcommunity.com/id/seiyria/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
